namespace: sd202105
name: demo
version: 0.0.1
readme: README.md
authors:
- Hideki Saito <saito@fgrep.org>
description: Demonstration collection for Software Design 2021.05
license:
- GPL-2.0-or-later
license_file: ''
tags:
  - demo
  - galaxy_ng
  - software_design
dependencies: {}
repository: http://
documentation: https://github.com/saito-hideki/sd202105
homepage: https://github.com/saito-hideki/sd202105
issues: https://github.com/saito-hideki/sd202105/issues
