---
- hosts: all
  vars:
    pulp_settings:
      content_origin: "https://galaxyng.example.com"
    pulp_default_admin_password: changeme
  tasks:
    - name: configure galaxy site
      import_role:
        name: ansible.galaxy_collection.post_install_config

    - name: gathering services on managed node
      service_facts:
      become: true

    - name: generate pulp service list
      set_fact:
        pulp_services: "{{ services | dict2items | selectattr('key', 'match', '^pulpcore-*') | rejectattr('key', 'match', '^pulpcore-worker*') | list | items2dict }}"

    - name: restart pulp service
      systemd:
        name: "{{ item.key }}"
        state: restarted
        daemon_reload: true
      with_dict: '{{ pulp_services }}'
      become: true
